export const weeksData = [
  {
    id: 1,
    name: "Mindfulness in Action",
    icon: "",
    color: "#f9e4d4",
    accent: "#e8855a",
    cover: "/assets/week1-300x292.png",
    days: [
      { image: "/assets/w1d1.png", title: "Retrospective Inpection", theme: "Start your day with intention", body: "Begin each morning with a small, meaningful ritual that anchors you in the present. Light a candle, breathe deeply, or write three things you're grateful for.", tasks: ["Set your intention for the day", "5-minute breathing exercise", "Write in your gratitude journal"] },
      { image: "/assets/w1d2.png", title: "Engage Your Senses", theme: "Sit down in a peaceful corner", body: "Spend time tuning into your body's signals. Notice areas of tension, fatigue, or comfort. Your body carries wisdom — learn to listen.", tasks: ["Full body scan meditation (10 min)", "Gentle stretching routine", "Hydration check — drink 8 glasses"] },
      { image: "/assets/w1d3.png", title: "Mind Mapping", theme: "Inergrate in Lifestyle", body: "Designate one hour today without screens. Use it to reconnect with yourself through reading, journaling, or simply being still.", tasks: ["Set phone to Do Not Disturb for 1 hour", "Pick up a physical book", "Sit in silence for 10 minutes"] },
      { image: "/assets/w1d4.png", title: "Full Body Stretches", theme: "Feed your body mindfully", body: "Cook or prepare at least one meal today with full attention and presence. Notice the colors, textures, and aromas. Eating is a form of self-love.", tasks: ["Cook one meal from scratch", "Eat without distractions", "Try a new ingredient or recipe"] },
      { image: "/assets/w1d5.png", title: "yes", theme: "Move because it feels good", body: "Choose movement that brings you joy — not punishment. Dance, walk, swim, stretch. The goal is pleasure, not performance.", tasks: ["30-minute joyful movement", "No calorie counting today", "Notice how movement changes your mood"] },
      { image: "/assets/w1d6.png", title: "Rest Deeply", theme: "Honor the art of doing nothing", body: "Rest is productive. Today, give yourself full permission to rest — a nap, an afternoon of stillness, or an early bedtime.", tasks: ["Take a 20-minute nap if needed", "No productivity guilt today", "Prepare a cozy, calming sleep environment"] },
      { image: "/assets/w1d7.png", title: "Week Reflection", theme: "Celebrate your first week", body: "Look back at your first week. What did you learn about yourself? Every step forward is worth celebrating.", tasks: ["Journal your Week 1 reflections", "Write 3 wins from this week", "Set one intention for Week 2"] },
    ],
  },
  {
    id: 2,
    name: "Self Reflection",
    icon: "",
    color: "#fff8e1",
    accent: "#f9a825",
    cover: "/assets/week2-300x296.png",
    days: [
      { image: "/assets/w2d1.png", title: "Reach Out", theme: "Strengthen a bond today", body: "Connection is a core human need. Reach out to someone you care about — not with a quick text, but with real presence and warmth.", tasks: ["Call (not text) one friend or family member", "Ask how they truly are", "Share something real about yourself"] },
      { image: "/assets/w2d2.png", title: "Self-Compassion", theme: "Be your own best friend", body: "Notice the way you speak to yourself today. Would you say these things to someone you love? Practice meeting yourself with the same kindness.", tasks: ["Catch 3 self-critical thoughts", "Reframe each one with compassion", "Write yourself a kind letter"] },
      { image: "/assets/w2d3.png", title: "Nature Connection", theme: "Ground yourself outdoors", body: "Spend time in nature — even briefly. Feel the ground beneath your feet, notice the sky, breathe fresh air.", tasks: ["20-minute outdoor walk", "Leave your headphones behind", "Collect one natural object that speaks to you"] },
      { image: "/assets/w2d4.png", title: "Creative Expression", theme: "Create without judgment", body: "Creativity is a form of self-connection. Draw, write, sing, cook — anything that lets your inner world out. There is no right or wrong here.", tasks: ["Spend 30 min on creative activity", "No comparing your work to others", "Share something you created (optional)"] },
      { image: "/assets/w2d5.png", title: "Boundary Check", theme: "Honor your limits", body: "Healthy relationships require healthy boundaries. Reflect on where you might be giving too much or allowing too little.", tasks: ["Identify one boundary you need to set", "Practice saying 'no' gently but firmly", "Journal about your relationship with boundaries"] },
      { image: "/assets/w2d6.png", title: "Gratitude Walk", theme: "Find beauty in the ordinary", body: "Take a slow, deliberate walk with one purpose: notice things you're grateful for.", tasks: ["30-minute gratitude walk", "List 10 things you noticed", "Tell someone what you appreciate about them"] },
      { image: "/assets/w2d7.png", title: "Week Reflection", theme: "Deepen your connections", body: "Review the connections you nurtured this week — with others, with nature, and with yourself.", tasks: ["Journal Week 2 reflections", "Name your most meaningful connection this week", "Set one intention for Week 3"] },
    ],
  },
  {
    id: 3,
    name: "Reformation",
    icon: "",
    color: "#e8f5e9",
    accent: "#43a047",
    cover: "/assets/week3-296x300.png",
    days: [
      { image: "/assets/w3d1.png", title: "Sleep Sanctuary", theme: "Transform your sleep space", body: "Your bedroom should be a temple of rest. Today, create the conditions for the deepest, most restorative sleep of your life.", tasks: ["Declutter your sleep space", "Lower room temperature", "No screens 1 hour before bed"] },
      { image: "/assets/w3d2.png", title: "Nervous System Reset", theme: "Calm the storm within", body: "Our nervous systems carry the weight of every stress. Today, actively signal safety to your body through gentle practices.", tasks: ["Cold water face splash (3x)", "4-7-8 breathing technique", "Gentle yoga or floor stretches"] },
      { image: "/assets/w3d3.png", title: "Slow Morning", theme: "Resist the rush", body: "Wake up 30 minutes earlier. Move slowly. Don't check your phone first thing. Let the morning be a gift you give to yourself.", tasks: ["Set alarm 30 min early", "Morning pages (3 pages of free writing)", "No phone for first 30 minutes"] },
      { image: "/assets/w3d4.png", title: "Herbal Ritual", theme: "Ancient comfort in a cup", body: "Prepare an herbal tea with full attention. Choose herbs that support what you need today.", tasks: ["Research herbal teas and their benefits", "Prepare tea as a ceremony", "Drink it in complete stillness"] },
      { image: "/assets/w3d5.png", title: "Release", theme: "Let go of what weighs you down", body: "Write down everything you've been holding onto — worries, resentments, to-dos, regrets. Then symbolically let them go.", tasks: ["Write your full mental load", "Release the list (burn or tear)", "Sit in 5 minutes of clear-minded silence"] },
      { image: "/assets/w3d6.png", title: "Water Healing", theme: "Cleanse and renew", body: "Water is restorative. Take a long, intentional bath or shower today. Treat it as a ritual of renewal.", tasks: ["Prepare a luxurious bath or shower", "Use your favorite scent", "Visualize releasing stress as water flows down"] },
      { image: "/assets/w3d7.png", title: "Week Reflection", theme: "You are restored", body: "Three weeks in. Your body and mind have absorbed so much goodness. You have done something remarkable by showing up.", tasks: ["Journal Week 3 reflections", "What has restored you most?", "Set your final week intention"] },
    ],
  },
  {
    id: 4,
    name: "Cultivation",
    icon: "",
    color: "#f3e5f5",
    accent: "#9c27b0",
    cover: "/assets/week4-300x298.png",
    days: [
      { image: "/assets/w4d1.png", title: "Vision Casting", theme: "See your future self", body: "Close your eyes and vividly imagine the version of you that is fully well, fully alive. What does she feel?", tasks: ["15-minute visualization meditation", "Write a letter from your future self", "Create a mini vision board"] },
      { image: "/assets/w4d2.png", title: "Joyful Living", theme: "Do more of what lights you up", body: "Make a list of everything that brings you pure joy — and do at least one today. Joy is not frivolous. It is essential.", tasks: ["Write your joy list", "Schedule joy into your week", "Do one joyful thing with full presence"] },
      { image: "/assets/w4d3.png", title: "Purpose Exploration", theme: "What are you here for?", body: "Purpose doesn't have to be grand. It can be as simple as making one person feel loved each day.", tasks: ["Journal: What would I do if I couldn't fail?", "Identify 3 things that feel meaningful", "Take one small step toward purpose"] },
      { image: "/assets/w4d4.png", title: "Celebrate You", theme: "You are worthy of celebration", body: "You showed up for 4 weeks. That is extraordinary. Today, celebrate yourself — simply your beautiful, worthy existence.", tasks: ["Buy yourself something small and meaningful", "Write 10 things you love about yourself", "Share your journey with someone you trust"] },
      { image: "/assets/w4d5.png", title: "Rituals Review", theme: "Keep what feeds your soul", body: "Look back at 28 days of practices. Which rituals felt like coming home? Which can you carry forward?", tasks: ["List your top 5 practices from 28 days", "Design a simple daily self-care ritual", "Write it somewhere visible"] },
      { image: "/assets/w4d6.png", title: "Give Back", theme: "Overflow into others", body: "When we are well-cared-for, we have more to give. Direct some of your overflowing love and care outward.", tasks: ["One act of kindness for a stranger", "Donate or volunteer (even 30 minutes)", "Write a heartfelt note to someone who helped you"] },
      { image: "/assets/w4d7.png", title: "The Journey Continues", theme: "This is just the beginning", body: "28 days. 28 small acts of self-love. This is not an ending — it is the beginning of how you live now.", tasks: ["Write your full 28-day reflection", "Set 3 intentions for the month ahead", "Celebrate — you bloomed."] },
    ],
  },
];
